theme: jekyll-theme-minimal
title: ADA ByggeMandBob
description: CMU Movie dataset
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Introduction
    url: pages/introduction
  - title: Distribution and cleaning
    url: pages/dist_and_clean
  - title: How does actor gender influence box office revenue?
    url: pages/gender
  - title: How does the movies original language affect the revenue and rating?
    url: original_language
  - title: Genres
    url: pages/genres
  - title: Natural Language Processing - a possible solution?
    url: pages/NLP_clustering
  - title: Bag of words
    url: pages/NLP_bagofwords
  - title: Using word2vec instead of bag of words
    url: pages/NLP_word2vec
  - title: How does the movies sentiment play in?
    url: pages/NLP_sentiment
  - title: Conclusion
    url: pages/conclusion

