theme: jekyll-theme-minimal
title: ADA ByggeMandBob
description: CMU Movie dataset
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
  - title: Distribution and cleaning
    url: dist_and_clean.md
